export const CLIENT_API_KEY_ACTIONS = {
  SET_KEY: "SET_API_KEY",
  CLEAR_KEY: "CLEAR_API_KEY",
};

export const CLIENT_SET_MEDIA_PREF_ACTIONS = {
  YOUTUBE: "SET_MEDIA_YOUTUBE",
  TWITTER: "SET_MEDIA_TWITTER",
  REDDIT: "SET_MEDIA_REDDIT",
  AMAZON: "SET_MEDIA_AMAZON",
};
