export const MEDIA_SET_ACTIONS = {
  COMMENTS: "SET_COMMENTS",
  MEDIA_ID: "SET_MEDIA_ID",
  CREATOR_INFO: "SET_CREATOR_INFO",
  VIDEO_INFO: "SET_VIDEO_INFO",
};

export const MEDIA_CLEAR_ACTIONS = {
  COMMENTS: "CLEAR_COMMENTS",
  MEDIA_ID: "CLEAR_MEDIA_ID",
  CREATOR_INFO: "CLEAR_CREATOR_INFO",
  VIDEO_INFO: "CLEAR_VIDEO_INFO",
};
